# Generated by Django 4.2.23 on 2025-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='programNote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
