# Generated by Django 4.2.23 on 2025-10-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_concert_programnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='mapLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
